environment:
  matrix:
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g npm@next

build: off

test_script:
  - node --version
  - npm --version
  - npm run-script test-ci

version: "{build}"

